--- !Ups

CREATE TABLE IF NOT EXISTS "profiles" (
                                        "profile_id"  BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,
                                        "name" VARCHAR (100) NOT NULL,
                                        "email" VARCHAR (100) NOT NULL UNIQUE
);

--- !Downs
DROP TABLE "profiles"